apiVersion: v1
kind: Service
metadata:
  name: python-backend
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: python-backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
